const fs = require('fs');
const content = fs.readFileSync('src/data.ts', 'utf8');

const newTasks = [
  {
    id: "TASK-003",
    title: "Innovation Hub Visualizer Kit",
    description: "",
    status: "col-done",
    priority: "medium",
    startDate: "2026-06-20",
    dueDate: "2026-06-20",
    assignee: "Abdallah",
    tags: [],
    estimatedHours: 5,
    actualHours: 5,
    location: "Office/Remote",
    notes: "Logged from Daily Logs board",
    subtasks: [],
    comments: [],
    createdAt: "2026-06-20"
  },
  {
    id: "TASK-006",
    title: "Test Run v0.2",
    description: "",
    status: "col-done",
    priority: "urgent",
    startDate: "2026-06-21",
    dueDate: "2026-06-21",
    assignee: "Abdallah",
    tags: [],
    estimatedHours: 1,
    actualHours: 1,
    location: "Office/Remote",
    notes: "[At 02:00 AM] Stest run of the visualizer V0.2",
    subtasks: [],
    comments: [],
    createdAt: "2026-06-21"
  },
  {
    id: "TASK-007",
    title: "ECE Measurement Test Out",
    description: "",
    status: "col-done",
    priority: "medium",
    startDate: "2026-06-21",
    dueDate: "2026-06-21",
    assignee: "Sallam",
    tags: [],
    estimatedHours: 8,
    actualHours: 8,
    location: "Office/Remote",
    notes: "[At 09:00 AM] ECE Department Measurement Testout Sessions",
    subtasks: [],
    comments: [],
    createdAt: "2026-06-21"
  },
  {
    id: "TASK-008",
    title: "Tasneem 3D Printing",
    description: "",
    status: "col-done",
    priority: "medium",
    startDate: "2026-06-22",
    dueDate: "2026-06-22",
    assignee: "Unassigned",
    tags: [],
    estimatedHours: 1,
    actualHours: 4,
    location: "Office/Remote",
    notes: "[At 09:00 AM]\n-D:\\Abdallah Salaheldean\\Innovation\\3D-Printing\\Tasneem Tarek Abdelkereem\\21-6-2026\\New Print 2023\\200 mm\\0_Taber ratio",
    subtasks: [],
    comments: [],
    createdAt: "2026-06-22"
  },
  {
    id: "TASK-009",
    title: "3D Printing Variable Layer Height",
    description: "",
    status: "col-done",
    priority: "medium",
    startDate: "2026-06-22",
    dueDate: "2026-06-22",
    assignee: "Unassigned",
    tags: [],
    estimatedHours: 1,
    actualHours: 1,
    location: "Office/Remote",
    notes: "[At 09:00 AM] - https://www.youtube.com/shorts/jVD0irMC4L8\n- Find a Model to try it out - Done\n- https://www.youtube.com/watch?v=gTQg5fSs_as&t=39s",
    subtasks: [],
    comments: [],
    createdAt: "2026-06-22"
  },
  {
    id: "TASK-010",
    title: "3D Printing Thermal Tower",
    description: "",
    status: "col-done",
    priority: "medium",
    startDate: "2026-06-22",
    dueDate: "2026-06-22",
    assignee: "Unassigned",
    tags: [],
    estimatedHours: 1,
    actualHours: 1,
    location: "Office/Remote",
    notes: "[At 09:00 AM] - https://www.youtube.com/watch?v=WR2tRwzFlq0&t=83s\n-https://www.printables.com/model/20652-temp-tower-pla-petg-absasa-for-prusa-mini-mk3s-and",
    subtasks: [],
    comments: [],
    createdAt: "2026-06-22"
  },
  {
    id: "TASK-011",
    title: "Masters",
    description: "",
    status: "col-done",
    priority: "urgent",
    startDate: "2026-06-20",
    dueDate: "2026-06-23",
    assignee: "Sallam",
    tags: [],
    estimatedHours: 10,
    actualHours: 0,
    location: "Remote",
    notes: "[At 09:00 AM]",
    subtasks: [],
    comments: [],
    createdAt: "2026-06-20"
  },
  {
    id: "TASK-012",
    title: "3DP G-Code",
    description: "",
    status: "col-done",
    priority: "medium",
    startDate: "2026-06-23",
    dueDate: "2026-06-24",
    assignee: "Abdallah",
    tags: [],
    estimatedHours: 4,
    actualHours: 4,
    location: "Office/Remote",
    notes: "[At 09:00 AM] Eng. Shad - Check that the G Code matches the prusa\n\n# ROLE\nYou are a G-code verification assistant. Your job is to examine a G-code file and determine whether it is safe to print on my specific 3D printer. Be precise and conservative: when something is ambiguous or missing, say so rather than assuming.\n\n# MY PRINTER (the target)\n- Model: Prusa i3 MK3S+ (MK3S-compatible G-code is fine)\n- Nozzle: 0.4 mm\n- Build volume: 250 (X) × 210 (Y) × 210 (Z) mm\n- Firmware: Marlin (Prusa fork)\n- File format expected: plain-text .gcode (NOT binary .bgcode)\n\n# WHAT TO DO\nRead the file's header/config comments AND scan the actual motion commands. Do not rely only on the comment block — verify against the real G-code body. Then run every check below and report findings.\n\n# HARD RULES (a FAIL on any of these = \"DO NOT PRINT\")\n1. NOZZLE: Find nozzle_diameter. If it is not 0.4 mm, FAIL.\n2. BUILD VOLUME: Scan all X/Y/Z coordinates in the motion commands. If any X > 250, Y > 210, or Z > 210, the model won't fit — FAIL. Report the max X, Y, Z actually reached.\n3. FLAVOR: Confirm the G-code flavor is Marlin. If it is Klipper, RepRap/Duet, Bambu/X1-specific, or anything non-Marlin, FAIL.\n4. PRINTER MODEL: Look for printer_model / compatible printers / settings IDs.\n - If it names a Prusa MK3S/MK3S+, PASS this check.\n - If it names a DIFFERENT printer (MK4, MINI, Ender, Bambu, etc.), FAIL.\n5. FILE TYPE: If the content is binary/garbled rather than readable text commands, it may be .bgcode — FAIL and tell me to re-export as plain G-code.\n6. UNSUPPORTED COMMANDS: Flag any machine-specific codes the Prusa Marlin firmware would not understand — e.g. AMS/multi-material toolchanges, vendor-only M-codes (Bambu, Klipper macros). Note them. Core moves (G0/G1/G2/G3, G28, G29, M104/M109/M140/M190, M106) are all fine.\n\n# SAFETY CHECKS (a problem here = \"PRINT WITH CAUTION\", not an automatic fail)\n7. TEMPERATURES: Report nozzle and bed temps (M104/M109/M140/M190). Flag if nozzle > 300 °C or bed > 120 °C, or if temps look wrong for the stated filament (e.g. PLA above ~230 °C, or 0 °C where heat is expected).\n8. MODEL-CHECK LINE: Note whether an M862.3 model-check line is present.\n - Present and matching MK3S = good, the printer will self-verify.\n - ABSENT (common when sliced in non-Prusa slicers like Bambu Studio or Cura) = the printer will NOT verify the model itself, so I'm trusting the profile. Tell me this so I watch the first layer.\n9. START/END SEQUENCE: Confirm there's a sane startup (home G28, usually mesh leveling G29, a purge/intro line) and a sane ending (turn off heaters M104 S0 / M140 S0, fan off M107, park, disable motors M84). Flag if missing.\n10. BED ORIGIN / OFFSETS: Note if coordinates look shifted off the bed or use an unexpected origin that could cause the nozzle to crash or print off-plate.\n\n# SLICER NOTE\nIdentify which slicer and version produced the file (from the header). It's OK if it's not PrusaSlicer (e.g. Bambu Studio or Cura targeting a Prusa profile) — just confirm the profile/settings actually target the MK3S and the rules above pass.\n\n# OUTPUT FORMAT (use exactly this)\n**VERDICT:** ✅ SAFE TO PRINT / ⚠️ PRINT WITH CAUTION / ❌ DO NOT PRINT\n\n**Sliced by:** <slicer + version>\n**Target printer in file:** <printer_model found>\n**Nozzle:** <value>\n**Max dimensions reached:** X__ Y__ Z__ (vs limits 250×210×210)\n**Flavor:** <Marlin / other>\n**Temps:** nozzle __°C, bed __°C (filament: __)\n**M862.3 model check:** present / absent\n**Start/End sequence:** ok / issues\n\n**Why:** <2–4 sentence plain explanation of the verdict>\n**Watch out for:** <anything I should monitor, or \"nothing — looks clean\">",
    subtasks: [],
    comments: [],
    createdAt: "2026-06-23"
  },
  {
    id: "TASK-013",
    title: "Robotino Day 2 Report",
    description: "",
    status: "col-done",
    priority: "medium",
    startDate: "2026-06-24",
    dueDate: "2026-06-25",
    assignee: "Unassigned",
    tags: [],
    estimatedHours: 1,
    actualHours: 1,
    location: "Office/Remote",
    notes: "[At 09:00 AM] Write a report and a LinkedIn link here",
    subtasks: [],
    comments: [],
    createdAt: "2026-06-24"
  },
  {
    id: "TASK-014",
    title: "Robotino Sessions",
    description: "",
    status: "col-done",
    priority: "medium",
    startDate: "2026-06-23",
    dueDate: "2026-06-26",
    assignee: "Unassigned",
    tags: [],
    estimatedHours: 32,
    actualHours: 8,
    location: "Office/Remote",
    notes: "[At 09:00 AM] Logged from Daily Logs board",
    subtasks: [],
    comments: [],
    createdAt: "2026-06-23"
  },
  {
    id: "TASK-015",
    title: "shahd printing files",
    description: "",
    status: "col-done",
    priority: "medium",
    startDate: "2026-06-24",
    dueDate: "2026-06-24",
    assignee: "Unassigned",
    tags: [],
    estimatedHours: 3,
    actualHours: 3,
    location: "Office/Remote",
    notes: "[At 09:00 AM] together\nD:\\sallam\\shahad\\G-codes for printing\nD638 Type 1 _50_Cubic_PLA+_31m31s_7.94g.gcode",
    subtasks: [],
    comments: [],
    createdAt: "2026-06-24"
  },
  {
    id: "TASK-016",
    title: "Tasneem 3D printing 200 mm",
    description: "",
    status: "col-done",
    priority: "low",
    startDate: "2026-06-24",
    dueDate: "2026-06-25",
    assignee: "Unassigned",
    tags: [],
    estimatedHours: 12,
    actualHours: 12,
    location: "Office/Remote",
    notes: "[At 09:00 AM] D:\\Abdallah Salaheldean\\Innovation\\3D-Printing\\Tasneem Tarek Abdelkereem\\21-6-2026\\New Print 2023\\200 mm\\0.2_Taber ratio",
    subtasks: [],
    comments: [],
    createdAt: "2026-06-24"
  },
  {
    id: "TASK-017",
    title: "Entity Survey : Eltoukhy Learning Factory",
    description: "",
    status: "col-done",
    priority: "medium",
    startDate: "2026-06-27",
    dueDate: "2026-06-27",
    assignee: "Abdallah",
    tags: [],
    estimatedHours: 4,
    actualHours: 4,
    location: "Office/Remote",
    notes: "[At 10:00 AM] Logged from Daily Logs board",
    subtasks: [],
    comments: [],
    createdAt: "2026-06-27"
  },
  {
    id: "TASK-018",
    title: "Entity Survey : Ain Shams University iHub",
    description: "",
    status: "col-done",
    priority: "medium",
    startDate: "2026-06-28",
    dueDate: "2026-06-29",
    assignee: "Abdallah",
    tags: [],
    estimatedHours: 4,
    actualHours: 4,
    location: "Office/Remote",
    notes: "[At 09:00 AM] Logged from Daily Logs board",
    subtasks: [],
    comments: [],
    createdAt: "2026-06-28"
  },
  {
    id: "TASK-019",
    title: "3D Printers Amr Safwat Report",
    description: "",
    status: "col-progress",
    priority: "medium",
    startDate: "2026-06-29",
    dueDate: "2026-06-29",
    assignee: "Sallam",
    tags: [],
    estimatedHours: 4,
    actualHours: 4,
    location: "Office/Remote",
    notes: "[At 10:45 AM] Logged from Daily Logs board",
    subtasks: [],
    comments: [],
    createdAt: "2026-06-29"
  },
  {
    id: "TASK-020",
    title: "3D Printing Shahd",
    description: "",
    status: "col-done",
    priority: "medium",
    startDate: "2026-06-29",
    dueDate: "2026-06-29",
    assignee: "Unassigned",
    tags: [],
    estimatedHours: 4,
    actualHours: 4,
    location: "Office/Remote",
    notes: "[At 09:00 AM] D:\\Abdallah Salaheldean\\Innovation\\3D-Printing\\Shahd\\25-06-2026\\1_D638 Type 1 _50_Grid_PLA+_32m14s_7.93g",
    subtasks: [],
    comments: [],
    createdAt: "2026-06-29"
  },
  {
    id: "TASK-021",
    title: "3D Printing Egals",
    description: "",
    status: "col-done",
    priority: "medium",
    startDate: "2026-06-29",
    dueDate: "2026-06-29",
    assignee: "Unassigned",
    tags: [],
    estimatedHours: 4,
    actualHours: 4,
    location: "Office/Remote",
    notes: "[At 09:00 AM] D:\\Abdallah Salaheldean\\Innovation\\3D-Printing\\Eagles\\28-06-2026\\air cover 1 p1",
    subtasks: [],
    comments: [],
    createdAt: "2026-06-29"
  },
  {
    id: "TASK-022",
    title: "Civil Shaker Request and Foam Cutting",
    description: "",
    status: "col-done",
    priority: "medium",
    startDate: "2026-06-29",
    dueDate: "2026-06-29",
    assignee: "Unassigned",
    tags: [],
    estimatedHours: 1,
    actualHours: 1,
    location: "Office/Remote",
    notes: "[At 04:00 PM] Logged from Daily Logs board",
    subtasks: [],
    comments: [],
    createdAt: "2026-06-29"
  },
  {
    id: "TASK-023",
    title: "Mohannad 3D Printing",
    description: "",
    status: "col-progress",
    priority: "medium",
    startDate: "2026-06-30",
    dueDate: "2026-06-30",
    assignee: "Unassigned",
    tags: [],
    estimatedHours: 4,
    actualHours: 4,
    location: "Office/Remote",
    notes: "[At 10:00 AM] Logged from Daily Logs board",
    subtasks: [],
    comments: [],
    createdAt: "2026-06-30"
  },
  {
    id: "TASK-024",
    title: "Shahd 3D Printing",
    description: "",
    status: "col-done",
    priority: "medium",
    startDate: "2026-06-30",
    dueDate: "2026-06-30",
    assignee: "Unassigned",
    tags: [],
    estimatedHours: 4,
    actualHours: 4,
    location: "Office/Remote",
    notes: "[At 09:00 AM] D:\\Abdallah Salaheldean\\Innovation\\3D-Printing\\Shahd\\25-06-2026\\2_D638 Type 1 _50_Honeycomb_PLA+_51m11s_8.43g.gcode",
    subtasks: [],
    comments: [],
    createdAt: "2026-06-30"
  },
  {
    id: "TASK-025",
    title: "Eman/David Thermal Device",
    description: "",
    status: "col-blocked",
    priority: "medium",
    startDate: "2026-06-30",
    dueDate: "2026-06-30",
    assignee: "Sallam",
    tags: [],
    estimatedHours: 4,
    actualHours: 4,
    location: "Office/Remote",
    notes: "[At 10:00 AM] Logged from Daily Logs board",
    subtasks: [],
    comments: [],
    createdAt: "2026-06-30"
  },
  {
    id: "TASK-026",
    title: "ESP-Cam 3D Printer and Tools Monitoring",
    description: "",
    status: "col-todo",
    priority: "medium",
    startDate: "2026-06-30",
    dueDate: "2026-06-30",
    assignee: "Abdallah",
    tags: [],
    estimatedHours: 4,
    actualHours: 4,
    location: "Office/Remote",
    notes: "[At 09:00 AM] Logged from Daily Logs board",
    subtasks: [],
    comments: [],
    createdAt: "2026-06-30"
  },
  {
    id: "TASK-027",
    title: "Electronic Workbench",
    description: "",
    status: "col-progress",
    priority: "medium",
    startDate: "2026-06-30",
    dueDate: "2026-06-30",
    assignee: "Abdallah",
    tags: [],
    estimatedHours: 4,
    actualHours: 4,
    location: "Office/Remote",
    notes: "[At 09:00 AM] Logged from Daily Logs board",
    subtasks: [],
    comments: [],
    createdAt: "2026-06-30"
  },
  {
    id: "TASK-028",
    title: "Ahmed Ibrahim",
    description: "",
    status: "col-blocked",
    priority: "medium",
    startDate: "2026-06-30",
    dueDate: "2026-06-30",
    assignee: "Unassigned",
    tags: [],
    estimatedHours: 4,
    actualHours: 4,
    location: "Office/Remote",
    notes: "[At 10:00 AM] Logged from Daily Logs board",
    subtasks: [],
    comments: [],
    createdAt: "2026-06-30"
  },
  {
    id: "TASK-029",
    title: "Claude Code Vercel Visualizer Web-Kit",
    description: "",
    status: "col-todo",
    priority: "medium",
    startDate: "2026-06-20",
    dueDate: "2026-06-20",
    assignee: "Abdallah",
    tags: [],
    estimatedHours: 10,
    actualHours: 0,
    location: "Remote",
    notes: "[At 09:00 AM]",
    subtasks: [],
    comments: [],
    createdAt: "2026-06-20"
  },
  {
    id: "TASK-030",
    title: "Eagles Printing",
    description: "",
    status: "col-progress",
    priority: "medium",
    startDate: "2026-07-06",
    dueDate: "2026-07-06",
    assignee: "Unassigned",
    tags: [],
    estimatedHours: 3,
    actualHours: 3,
    location: "Office/Remote",
    notes: "[At 11:00 AM] Logged from Daily Logs board",
    subtasks: [],
    comments: [],
    createdAt: "2026-07-06"
  },
  {
    id: "TASK-031",
    title: "HPDE Manfacting With Civil Eng. Mohammed Mohsen",
    description: "",
    status: "col-progress",
    priority: "medium",
    startDate: "2026-07-06",
    dueDate: "2026-07-06",
    assignee: "Unassigned",
    tags: [],
    estimatedHours: 4,
    actualHours: 4,
    location: "Office/Remote",
    notes: "[At 01:00 PM] Logged from Daily Logs board",
    subtasks: [],
    comments: [],
    createdAt: "2026-07-06"
  },
  {
    id: "TASK-032",
    title: "Prusa Thermal Modle Error",
    description: "",
    status: "col-progress",
    priority: "medium",
    startDate: "2026-07-06",
    dueDate: "2026-07-06",
    assignee: "Abdallah",
    tags: [],
    estimatedHours: 4,
    actualHours: 4,
    location: "Office/Remote",
    notes: "[At 10:00 AM] Logged from Daily Logs board",
    subtasks: [],
    comments: [],
    createdAt: "2026-07-06"
  }
];

const match = content.match(/tasks: \[([\s\S]*?)\]\n\s+\}\n\];/);
if (match) {
  const newTasksString = JSON.stringify(newTasks, null, 2).replace(/^/gm, '    ').trim();
  const updated = content.replace(match[0], `tasks: ${newTasksString}\n  }\n];`);
  fs.writeFileSync('src/data.ts', updated, 'utf8');
  console.log("Updated data.ts");
} else {
  console.log("Could not find tasks array to replace");
}
