import { Project, IdeaItem } from "./types";

export const INITIAL_PROJECTS: Project[] = [
  {
    id: "proj-innovation-hub",
    name: "💻 Code of Innovation Hub",
    description: "Master workspace for tracking the design, electronics, fabrication, and smart systems of the Innovation Hub.",
    tags: ["Electronics", "Fabrication", "3D Printing", "Software", "Safety", "Admin"],
    columns: [
      { id: "col-todo", title: "Not Started", color: "#64748b" },
      { id: "col-progress", title: "In Progress", color: "#3b82f6" },
      { id: "col-blocked", title: "Blocked", color: "#f43f5e" },
      { id: "col-done", title: "Completed", color: "#10b981" },
    ],
    teams: [
      { id: "team-sw", name: "Software Team", description: "Cloud services, dynamic dashboards, and embedded firmware code." },
      { id: "team-hw", name: "Hardware & IoT", description: "Microcontrollers, sensor calibration, and radio transceiver grids." },
      { id: "team-fab", name: "Fabrication & Design", description: "CAD design, laser alignments, and 3D printing assemblies." },
      { id: "team-ops", name: "Operations & Safety", description: "Workspace regulatory guidelines, safety logs, and asset logging." }
    ],
    members: [
      { id: "m-abdallah", name: "Abdallah", role: "Innovation Lead", email: "abdallah.salaheldean@gmail.com", teamId: "team-sw", avatar: "A", bg: "bg-indigo-600" },
      { id: "m-sallam", name: "Sallam", role: "Systems Engineer", email: "sallam.workspace@gmail.com", teamId: "team-hw", avatar: "S", bg: "bg-blue-600" },
      { id: "m-alice", "name": "Alice", role: "Lab Contributor", email: "alice@workspace.io", teamId: "team-fab", avatar: "A", bg: "bg-emerald-600" },
      { id: "m-bob", "name": "Bob", "role": "Lab Contributor", email: "bob@workspace.io", teamId: "team-hw", avatar: "B", bg: "bg-indigo-500" },
      { id: "m-charlie", "name": "Charlie", "role": "Lab Contributor", email: "charlie@workspace.io", teamId: "team-sw", avatar: "C", bg: "bg-slate-700" },
      { id: "m-diana", "name": "Diana", "role": "Lab Contributor", email: "diana@workspace.io", teamId: "team-ops", avatar: "D", bg: "bg-amber-600" }
    ],
    ideas: [
      {
        id: "idea-001",
        timeHorizon: "Next Month",
        title: "Define policies & entities",
        description: "Draft comprehensive user guidelines and laboratory structure details for external access.",
        targetDate: "2024-02-15",
        status: "Not Started",
        priority: "High",
        zone: "Zone 1: Ready to Start - Important & Urgent"
      },
      {
        id: "idea-002",
        timeHorizon: "Next Month",
        title: "Build fixed-asset report (safety focus)",
        description: "Create an integrated visual audit sheet to report device safety compliance.",
        targetDate: "2024-02-20",
        status: "In Progress",
        priority: "Critical",
        zone: "Zone 1: Ready to Start - Important & Urgent"
      },
      {
        id: "idea-003",
        timeHorizon: "Next Month",
        title: "Roll out QR-code system for assets",
        description: "Affix QR labels to all hardware to enable rapid smartphone scans for details.",
        targetDate: "2024-02-28",
        status: "Not Started",
        priority: "High",
        zone: "Zone 1: Ready to Start - Important & Urgent"
      },
      {
        id: "idea-004",
        timeHorizon: "Someday",
        title: "Safety: manufacturing lab & all equipment",
        description: "Perform end-to-end certification of advanced heavy-duty machinery.",
        targetDate: "2024-06-01",
        status: "On Hold",
        priority: "Medium",
        zone: "Zone 4: On Hold / Wishlist - Not Important & Not Urgent"
      },
      {
        id: "idea-005",
        timeHorizon: "Someday",
        title: "CNC Router - register as fixed asset",
        description: "Process catalog documents and tags for the newly procured computer-controlled carver.",
        targetDate: "2024-05-15",
        status: "On Hold",
        priority: "Low",
        zone: "Zone 4: On Hold / Wishlist - Not Important & Not Urgent"
      }
    ],
    tasks: [
      // --- ABDALLAH'S TASKS (9 total) ---
      // Completed (5)
      {
        id: "TASK-003",
        title: "Innovation Hub Visualizer Kit",
        description: "Assemble and calibrate the sensor projection rig and test software dashboard connectivity.",
        status: "col-done",
        priority: "high",
        startDate: "2024-01-03",
        dueDate: "2024-01-07",
        assignee: "Abdallah",
        tags: ["Software", "Electronics"],
        estimatedHours: 12,
        actualHours: 10,
        location: "Electronics Bay",
        notes: "Calibrated successfully under ambient light.",
        subtasks: [
          { id: "sub-3-1", title: "Mount sensors onto frame", completed: true },
          { id: "sub-3-2", title: "Run calibration routine", completed: true }
        ],
        comments: [],
        createdAt: "2024-01-03"
      },
      {
        id: "TASK-006",
        title: "Test Run v0.2",
        description: "Execute end-to-end system test of wireless logger relay nodes under peak loads.",
        status: "col-done",
        priority: "medium",
        startDate: "2024-01-05",
        dueDate: "2024-01-08",
        assignee: "Abdallah",
        tags: ["Software", "Electronics"],
        estimatedHours: 8,
        actualHours: 8,
        location: "Server Rack",
        notes: "Relay latencies remained below 45ms.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-05"
      },
      {
        id: "TASK-010",
        title: "Laser Cutter Calibration & Alignment",
        description: "Align optical mirrors and recalibrate focus lens for precise material cutting sheets.",
        status: "col-done",
        priority: "high",
        startDate: "2024-01-02",
        dueDate: "2024-01-05",
        assignee: "Abdallah",
        tags: ["Fabrication", "Safety"],
        estimatedHours: 6,
        actualHours: 5,
        location: "Fabrication Room",
        notes: "Mirror alignment checked; burn pattern test successful.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-02"
      },
      {
        id: "TASK-011",
        title: "Raspberry Pi Micro-Server Provisioning",
        description: "Deploy Node-RED and Docker containers onto lab supervisor server node.",
        status: "col-done",
        priority: "medium",
        startDate: "2024-01-04",
        dueDate: "2024-01-06",
        assignee: "Abdallah",
        tags: ["Software"],
        estimatedHours: 5,
        actualHours: 5,
        location: "Server Rack",
        notes: "Configured static IP 192.168.1.150.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-04"
      },
      {
        id: "TASK-012",
        title: "Soldering Station Safety Signage",
        description: "Design and print eye protection warning sheets to hang over active soldering workbenches.",
        status: "col-done",
        priority: "low",
        startDate: "2024-01-08",
        dueDate: "2024-01-09",
        assignee: "Abdallah",
        tags: ["Safety"],
        estimatedHours: 2,
        actualHours: 2,
        location: "Electronics Bay",
        notes: "Laminated and mounted near ventilation controls.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-08"
      },
      // In Progress (2)
      {
        id: "TASK-013",
        title: "Interactive Workspace Dashboard Design",
        description: "Draft responsive mockup of room sensor logs and real-time power metrics.",
        status: "col-progress",
        priority: "medium",
        startDate: "2024-01-10",
        dueDate: "2024-01-15",
        assignee: "Abdallah",
        tags: ["Software"],
        estimatedHours: 15,
        actualHours: 8,
        location: "Main Desk",
        notes: "Frontend layout completed; connecting API proxies next.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-10"
      },
      {
        id: "TASK-014",
        title: "Oculus Quest VR Development Setup",
        description: "Set up Unity VR interaction kits and profile render targets for visualizer preview.",
        status: "col-progress",
        priority: "high",
        startDate: "2024-01-12",
        dueDate: "2024-01-16",
        assignee: "Abdallah",
        tags: ["Software"],
        estimatedHours: 10,
        actualHours: 4,
        location: "VR Sandbox",
        notes: "Connected headsets; loaded initial workspace mesh.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-12"
      },
      // Not Started (2)
      {
        id: "TASK-015",
        title: "Network Switch Rack Mounting",
        description: "Install 24-port Gigabit switch into secondary rack cabinet and label ports.",
        status: "col-todo",
        priority: "medium",
        startDate: "2024-01-18",
        dueDate: "2024-01-20",
        assignee: "Abdallah",
        tags: ["Electronics"],
        estimatedHours: 4,
        actualHours: 0,
        location: "Server Rack",
        notes: "Awaiting delivery of mounting brackets.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-15"
      },
      {
        id: "TASK-016",
        title: "Smart Power Outlet Integration",
        description: "Connect WiFi power strips to supervisor API for remote emergency shutdown tests.",
        status: "col-todo",
        priority: "high",
        startDate: "2024-01-22",
        dueDate: "2024-01-25",
        assignee: "Abdallah",
        tags: ["Electronics", "Safety"],
        estimatedHours: 6,
        actualHours: 0,
        location: "Electronics Bay",
        notes: "To be configured once network layout is complete.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-15"
      },

      // --- SALLAM'S TASKS (4 total) ---
      // Completed (2)
      {
        id: "TASK-007",
        title: "ECE Measurement Test Out",
        description: "Validate lab electrical tools and compile certification reports for local inspectors.",
        status: "col-done",
        priority: "high",
        startDate: "2024-01-04",
        dueDate: "2024-01-07",
        assignee: "Sallam",
        tags: ["Electronics", "Safety"],
        estimatedHours: 10,
        actualHours: 9,
        location: "Electronics Bay",
        notes: "Passed validation on all 12 multi-meter units.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-04"
      },
      {
        id: "TASK-017",
        title: "Oscilloscope Probe Diagnostics",
        description: "Check impedance matching and signal degradation on 100MHz channels.",
        status: "col-done",
        priority: "medium",
        startDate: "2024-01-03",
        dueDate: "2024-01-05",
        assignee: "Sallam",
        tags: ["Electronics"],
        estimatedHours: 4,
        actualHours: 4,
        location: "Electronics Bay",
        notes: "Two faulty probes replaced with spares.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-03"
      },
      // In Progress (1)
      {
        id: "TASK-018",
        title: "Digital Signal Generator Calibration",
        description: "Calibrate sine and square wave outputs to match high-precision standards.",
        status: "col-progress",
        priority: "medium",
        startDate: "2024-01-11",
        dueDate: "2024-01-14",
        assignee: "Sallam",
        tags: ["Electronics"],
        estimatedHours: 8,
        actualHours: 4,
        location: "Electronics Bay",
        notes: "Coarse tuning complete; fine calibration scheduled for tomorrow.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-11"
      },
      // Blocked (1)
      {
        id: "TASK-019",
        title: "PCB Milling Machine Spindle Fix",
        description: "Replace degraded ball bearings in high-speed rotary carving motor spindle.",
        status: "col-blocked",
        priority: "high",
        startDate: "2024-01-09",
        dueDate: "2024-01-12",
        assignee: "Sallam",
        tags: ["Fabrication"],
        estimatedHours: 12,
        actualHours: 6,
        location: "Fabrication Room",
        notes: "🛑 Awaiting delivery of specialized 8mm ceramic replacement bearings.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-09"
      },

      // --- UNASSIGNED TASKS (15 total) ---
      // Completed (11)
      {
        id: "TASK-008",
        title: "Tasneem 3D Printing",
        description: "Fabricate intricate structural frame pieces using biodegradable PLA filament.",
        status: "col-done",
        priority: "medium",
        startDate: "2024-01-05",
        dueDate: "2024-01-06",
        assignee: "Unassigned",
        tags: ["3D Printing"],
        estimatedHours: 4,
        actualHours: 3,
        location: "3D Printing Hub",
        notes: "Printed on Prusa i3 MK3S successfully.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-05"
      },
      {
        id: "TASK-001",
        title: "PCB Milling Machine Setup",
        description: "Clean dust trays, align sacrificial table boards, and lubricate guide rails.",
        status: "col-done",
        priority: "high",
        startDate: "2024-01-02",
        dueDate: "2024-01-04",
        assignee: "Unassigned",
        tags: ["Fabrication"],
        estimatedHours: 6,
        actualHours: 6,
        location: "Fabrication Room",
        notes: "All axes lubricated; limit switches functioning.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-02"
      },
      {
        id: "TASK-002",
        title: "Smart Locker Integration Setup",
        description: "Mount physical door solenoid locks and test offline RFID keychain scanners.",
        status: "col-done",
        priority: "medium",
        startDate: "2024-01-02",
        dueDate: "2024-01-04",
        assignee: "Unassigned",
        tags: ["Electronics", "Software"],
        estimatedHours: 8,
        actualHours: 8,
        location: "Main Entry",
        notes: "Solenoids functioning perfectly on local test bus.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-02"
      },
      {
        id: "TASK-004",
        title: "Oculus Rift S Sensor Calibration",
        description: "Calibrate secondary optical tracking cameras around physical desk volume.",
        status: "col-done",
        priority: "low",
        startDate: "2024-01-04",
        dueDate: "2024-01-05",
        assignee: "Unassigned",
        tags: ["Software"],
        estimatedHours: 3,
        actualHours: 3,
        location: "VR Sandbox",
        notes: "Sensors mounted at 2.1 meters height; latency resolved.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-04"
      },
      {
        id: "TASK-005",
        title: "3D Filament Inventory Count",
        description: "Count, tag, and moisture-seal unused PLA, ABS, and PETG filament spools.",
        status: "col-done",
        priority: "low",
        startDate: "2024-01-04",
        dueDate: "2024-01-05",
        assignee: "Unassigned",
        tags: ["3D Printing"],
        estimatedHours: 3,
        actualHours: 3,
        location: "3D Printing Hub",
        notes: "Total 24kg of filament cataloged and desiccated.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-04"
      },
      {
        id: "TASK-009",
        title: "Laser Cutter Air Filter Change",
        description: "Replace carbon honeycomb filters and clean primary blower exhaust hose.",
        status: "col-done",
        priority: "high",
        startDate: "2024-01-03",
        dueDate: "2024-01-04",
        assignee: "Unassigned",
        tags: ["Fabrication", "Safety"],
        estimatedHours: 4,
        actualHours: 4,
        location: "Fabrication Room",
        notes: "Filters replaced; airflow rate restored to nominal.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-03"
      },
      {
        id: "TASK-020",
        title: "Inventory Catalog Verification",
        description: "Crosscheck digital asset ledger with physical storage lockers in main bay.",
        status: "col-done",
        priority: "medium",
        startDate: "2024-01-02",
        dueDate: "2024-01-04",
        assignee: "Unassigned",
        tags: ["Admin"],
        estimatedHours: 6,
        actualHours: 6,
        location: "Main Desk",
        notes: "Discrepancy in multi-meter counts resolved.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-02"
      },
      {
        id: "TASK-021",
        title: "Filament Spool Sorting & Storage",
        description: "Re-organize vertical spool hangers by color temperature and type tags.",
        status: "col-done",
        priority: "low",
        startDate: "2024-01-06",
        dueDate: "2024-01-07",
        assignee: "Unassigned",
        tags: ["3D Printing"],
        estimatedHours: 3,
        actualHours: 3,
        location: "3D Printing Hub",
        notes: "Hangers clearly labeled.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-06"
      },
      {
        id: "TASK-022",
        title: "Lab Workbench De-cluttering",
        description: "Clear loose resistors, cut wires, and tape scraps from primary bays.",
        status: "col-done",
        priority: "low",
        startDate: "2024-01-08",
        dueDate: "2024-01-08",
        assignee: "Unassigned",
        tags: ["Safety"],
        estimatedHours: 2,
        actualHours: 2,
        location: "Electronics Bay",
        notes: "All workbenches wiped down.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-08"
      },
      {
        id: "TASK-023",
        title: "LED Strip Lighting Assembly",
        description: "Mount RGB utility light tracks underneath active storage cabinets.",
        status: "col-done",
        priority: "medium",
        startDate: "2024-01-04",
        dueDate: "2024-01-05",
        assignee: "Unassigned",
        tags: ["Electronics"],
        estimatedHours: 4,
        actualHours: 4,
        location: "Main Bay",
        notes: "Lighting successfully powered via 12V supply.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-04"
      },
      {
        id: "TASK-024",
        title: "Resistor & Capacitor Box Labeling",
        description: "Sort incoming component packages and print clear value labels.",
        status: "col-done",
        priority: "low",
        startDate: "2024-01-07",
        dueDate: "2024-01-08",
        assignee: "Unassigned",
        tags: ["Admin", "Electronics"],
        estimatedHours: 3,
        actualHours: 3,
        location: "Electronics Bay",
        notes: "Boxes 1 through 10 fully updated.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-07"
      },
      // In Progress (3)
      {
        id: "TASK-030",
        title: "3D Printer Extruder Head Cleaning",
        description: "Clear carbonized filament deposits from copper nozzles on printer unit #3.",
        status: "col-progress",
        priority: "medium",
        startDate: "2024-01-12",
        dueDate: "2024-01-14",
        assignee: "Unassigned",
        tags: ["3D Printing"],
        estimatedHours: 4,
        actualHours: 1,
        location: "3D Printing Hub",
        notes: "Soaking nozzle in solvent.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-12"
      },
      {
        id: "TASK-031",
        title: "Multimeter Battery Replacements",
        description: "Open battery compartments on 8 units and install brand-new 9V batteries.",
        status: "col-progress",
        priority: "low",
        startDate: "2024-01-13",
        dueDate: "2024-01-15",
        assignee: "Unassigned",
        tags: ["Electronics", "Safety"],
        estimatedHours: 3,
        actualHours: 1,
        location: "Electronics Bay",
        notes: "3/8 completed.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-13"
      },
      {
        id: "TASK-032",
        title: "Innovation Hub Website Updates",
        description: "Post updated safety regulations and device reservation procedures.",
        status: "col-progress",
        priority: "medium",
        startDate: "2024-01-10",
        dueDate: "2024-01-16",
        assignee: "Unassigned",
        tags: ["Software", "Admin"],
        estimatedHours: 12,
        actualHours: 6,
        location: "Main Desk",
        notes: "Drafted safety update section.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-10"
      },
      // Blocked (1)
      {
        id: "TASK-033",
        title: "Vinyl Cutter Software Driver Patch",
        description: "Verify operational cuts and patch software driver for compatibility under newer macOS.",
        status: "col-blocked",
        priority: "medium",
        startDate: "2024-01-11",
        dueDate: "2024-01-14",
        assignee: "Unassigned",
        tags: ["Software", "Fabrication"],
        estimatedHours: 6,
        actualHours: 2,
        location: "Fabrication Room",
        notes: "🛑 Blocked: Driver installer returns legacy architectural signature error.",
        subtasks: [],
        comments: [],
        createdAt: "2024-01-11"
      }
    ]
  }
];

export const TEAM_MEMBERS = [
  "Abdallah",
  "Sallam",
  "Unassigned",
  "Alice",
  "Bob",
  "Charlie",
  "Diana"
];

export const PRIORITIES: { value: "low" | "medium" | "high" | "urgent"; label: string; color: string; bg: string }[] = [
  { value: "low", label: "Low", color: "#94a3b8", bg: "bg-slate-800/60 text-slate-300 border-slate-700" },
  { value: "medium", label: "Medium", color: "#3b82f6", bg: "bg-blue-500/10 text-blue-400 border-blue-500/20" },
  { value: "high", label: "High", color: "#f59e0b", bg: "bg-amber-500/10 text-amber-400 border-amber-500/20" },
  { value: "urgent", label: "Critical", color: "#f43f5e", bg: "bg-red-500/10 text-red-400 border-red-500/20" },
];
